#!/bin/bash
# The command to call phpDocumentor 3 (see readme.md / wiki for more information)
phpdoccmd='[Name of the phpDocumentor command]'
# the path to the git wiki repository
wikidir='[path to the local git wiki repository]'

if [ $1 = '-b' ] || [ $1 = '-build' ]; then
    echo Build github wiki
    $phpdoccmd run -c githubwiki.xml
fi

if [ $1 = '-p' ] || [ $1 = '-publish' ]; then
    echo commit all changes and push to wiki master
    curdir=$PWD
    cd $wikidir
    git pull origin master
    git add --all
    git commit -a -m "phpDoc build $(date)"
    git push origin master
    cd $curdir
fi


